node inclusao_condicional geral/gen.txt tr/gen.txt tr trnc
node inclusao_condicional geral/exod.txt tr/exod.txt tr trnc
node inclusao_condicional geral/lev.txt tr/lev.txt tr trnc
node inclusao_condicional geral/num.txt tr/num.txt tr trnc
node inclusao_condicional geral/deut.txt tr/deut.txt tr trnc
node inclusao_condicional geral/jos.txt tr/jos.txt tr trnc
node inclusao_condicional geral/juiz.txt tr/juiz.txt tr trnc
node inclusao_condicional geral/rute.txt tr/rute.txt tr trnc
node inclusao_condicional geral/1sa.txt tr/1sa.txt tr trnc
node inclusao_condicional geral/2sa.txt tr/2sa.txt tr trnc
node inclusao_condicional geral/1rs.txt tr/1rs.txt tr trnc
node inclusao_condicional geral/2rs.txt tr/2rs.txt tr trnc
node inclusao_condicional geral/1crn.txt tr/1crn.txt tr trnc
node inclusao_condicional geral/2crn.txt tr/2crn.txt tr trnc
node inclusao_condicional geral/esd.txt tr/esd.txt tr trnc
node inclusao_condicional geral/nee.txt tr/nee.txt tr trnc
node inclusao_condicional geral/est.txt tr/est.txt tr trnc
node inclusao_condicional geral/jo.txt tr/jo.txt tr trnc
node inclusao_condicional geral/sal.txt tr/sal.txt tr trnc
node inclusao_condicional geral/prov.txt tr/prov.txt tr trnc
node inclusao_condicional geral/ecl.txt tr/ecl.txt tr trnc
node inclusao_condicional geral/cant.txt tr/cant.txt tr trnc
node inclusao_condicional geral/isa.txt tr/isa.txt tr trnc
node inclusao_condicional geral/jer.txt tr/jer.txt tr trnc
node inclusao_condicional geral/lam.txt tr/lam.txt tr trnc
node inclusao_condicional geral/eze.txt tr/eze.txt tr trnc
node inclusao_condicional geral/dan.txt tr/dan.txt tr trnc
node inclusao_condicional geral/ose.txt tr/ose.txt tr trnc
node inclusao_condicional geral/joel.txt tr/joel.txt tr trnc
node inclusao_condicional geral/amos.txt tr/amos.txt tr trnc
node inclusao_condicional geral/oba.txt tr/oba.txt tr trnc
node inclusao_condicional geral/jon.txt tr/jon.txt tr trnc
node inclusao_condicional geral/miq.txt tr/miq.txt tr trnc
node inclusao_condicional geral/naum.txt tr/naum.txt tr trnc
node inclusao_condicional geral/hab.txt tr/hab.txt tr trnc
node inclusao_condicional geral/sof.txt tr/sof.txt tr trnc
node inclusao_condicional geral/ageu.txt tr/ageu.txt tr trnc
node inclusao_condicional geral/zac.txt tr/zac.txt tr trnc
node inclusao_condicional geral/mal.txt tr/mal.txt tr trnc
node inclusao_condicional geral/mat.txt tr/mat.txt tr trnc
node inclusao_condicional geral/mar.txt tr/mar.txt tr trnc
node inclusao_condicional geral/luc.txt tr/luc.txt tr trnc
node inclusao_condicional geral/joao.txt tr/joao.txt tr trnc
node inclusao_condicional geral/atos.txt tr/atos.txt tr trnc
node inclusao_condicional geral/rom.txt tr/rom.txt tr trnc
node inclusao_condicional geral/1cor.txt tr/1cor.txt tr trnc
node inclusao_condicional geral/2cor.txt tr/2cor.txt tr trnc
node inclusao_condicional geral/gal.txt tr/gal.txt tr trnc
node inclusao_condicional geral/efes.txt tr/efes.txt tr trnc
node inclusao_condicional geral/fil.txt tr/fil.txt tr trnc
node inclusao_condicional geral/col.txt tr/col.txt tr trnc
node inclusao_condicional geral/1tes.txt tr/1tes.txt tr trnc
node inclusao_condicional geral/2tes.txt tr/2tes.txt tr trnc
node inclusao_condicional geral/1tim.txt tr/1tim.txt tr trnc
node inclusao_condicional geral/2tim.txt tr/2tim.txt tr trnc
node inclusao_condicional geral/tito.txt tr/tito.txt tr trnc
node inclusao_condicional geral/flm.txt tr/flm.txt tr trnc
node inclusao_condicional geral/heb.txt tr/heb.txt tr trnc
node inclusao_condicional geral/tiag.txt tr/tiag.txt tr trnc
node inclusao_condicional geral/1ped.txt tr/1ped.txt tr trnc
node inclusao_condicional geral/2ped.txt tr/2ped.txt tr trnc
node inclusao_condicional geral/1joao.txt tr/1joao.txt tr trnc
node inclusao_condicional geral/2joao.txt tr/2joao.txt tr trnc
node inclusao_condicional geral/3joao.txt tr/3joao.txt tr trnc
node inclusao_condicional geral/jud.txt tr/jud.txt tr trnc
node inclusao_condicional geral/apo.txt tr/apo.txt tr trnc
