node inclusao_condicional geral/gen.txt n4/gen.txt n4
node inclusao_condicional geral/exod.txt n4/exod.txt n4
node inclusao_condicional geral/lev.txt n4/lev.txt n4
node inclusao_condicional geral/num.txt n4/num.txt n4
node inclusao_condicional geral/deut.txt n4/deut.txt n4
node inclusao_condicional geral/jos.txt n4/jos.txt n4
node inclusao_condicional geral/juiz.txt n4/juiz.txt n4
node inclusao_condicional geral/rute.txt n4/rute.txt n4
node inclusao_condicional geral/1sa.txt n4/1sa.txt n4
node inclusao_condicional geral/2sa.txt n4/2sa.txt n4
node inclusao_condicional geral/1rs.txt n4/1rs.txt n4
node inclusao_condicional geral/2rs.txt n4/2rs.txt n4
node inclusao_condicional geral/1crn.txt n4/1crn.txt n4
node inclusao_condicional geral/2crn.txt n4/2crn.txt n4
node inclusao_condicional geral/esd.txt n4/esd.txt n4
node inclusao_condicional geral/nee.txt n4/nee.txt n4
node inclusao_condicional geral/est.txt n4/est.txt n4
node inclusao_condicional geral/jo.txt n4/jo.txt n4
node inclusao_condicional geral/sal.txt n4/sal.txt n4
node inclusao_condicional geral/prov.txt n4/prov.txt n4
node inclusao_condicional geral/ecl.txt n4/ecl.txt n4
node inclusao_condicional geral/cant.txt n4/cant.txt n4
node inclusao_condicional geral/isa.txt n4/isa.txt n4
node inclusao_condicional geral/jer.txt n4/jer.txt n4
node inclusao_condicional geral/lam.txt n4/lam.txt n4
node inclusao_condicional geral/eze.txt n4/eze.txt n4
node inclusao_condicional geral/dan.txt n4/dan.txt n4
node inclusao_condicional geral/ose.txt n4/ose.txt n4
node inclusao_condicional geral/joel.txt n4/joel.txt n4
node inclusao_condicional geral/amos.txt n4/amos.txt n4
node inclusao_condicional geral/oba.txt n4/oba.txt n4
node inclusao_condicional geral/jon.txt n4/jon.txt n4
node inclusao_condicional geral/miq.txt n4/miq.txt n4
node inclusao_condicional geral/naum.txt n4/naum.txt n4
node inclusao_condicional geral/hab.txt n4/hab.txt n4
node inclusao_condicional geral/sof.txt n4/sof.txt n4
node inclusao_condicional geral/ageu.txt n4/ageu.txt n4
node inclusao_condicional geral/zac.txt n4/zac.txt n4
node inclusao_condicional geral/mal.txt n4/mal.txt n4
node inclusao_condicional geral/mat.txt n4/mat.txt n4
node inclusao_condicional geral/mar.txt n4/mar.txt n4
node inclusao_condicional geral/luc.txt n4/luc.txt n4
node inclusao_condicional geral/joao.txt n4/joao.txt n4
node inclusao_condicional geral/atos.txt n4/atos.txt n4
node inclusao_condicional geral/rom.txt n4/rom.txt n4
node inclusao_condicional geral/1cor.txt n4/1cor.txt n4
node inclusao_condicional geral/2cor.txt n4/2cor.txt n4
node inclusao_condicional geral/gal.txt n4/gal.txt n4
node inclusao_condicional geral/efes.txt n4/efes.txt n4
node inclusao_condicional geral/fil.txt n4/fil.txt n4
node inclusao_condicional geral/col.txt n4/col.txt n4
node inclusao_condicional geral/1tes.txt n4/1tes.txt n4
node inclusao_condicional geral/2tes.txt n4/2tes.txt n4
node inclusao_condicional geral/1tim.txt n4/1tim.txt n4
node inclusao_condicional geral/2tim.txt n4/2tim.txt n4
node inclusao_condicional geral/tito.txt n4/tito.txt n4
node inclusao_condicional geral/flm.txt n4/flm.txt n4
node inclusao_condicional geral/heb.txt n4/heb.txt n4
node inclusao_condicional geral/tiag.txt n4/tiag.txt n4
node inclusao_condicional geral/1ped.txt n4/1ped.txt n4
node inclusao_condicional geral/2ped.txt n4/2ped.txt n4
node inclusao_condicional geral/1joao.txt n4/1joao.txt n4
node inclusao_condicional geral/2joao.txt n4/2joao.txt n4
node inclusao_condicional geral/3joao.txt n4/3joao.txt n4
node inclusao_condicional geral/jud.txt n4/jud.txt n4
node inclusao_condicional geral/apo.txt n4/apo.txt n4
