node convert_to_usfm tr/gen.txt tr_usfm/gen.usfm translation-tr.txt
node convert_to_usfm tr/exod.txt tr_usfm/exod.usfm translation-tr.txt
node convert_to_usfm tr/lev.txt tr_usfm/lev.usfm translation-tr.txt
node convert_to_usfm tr/num.txt tr_usfm/num.usfm translation-tr.txt
node convert_to_usfm tr/deut.txt tr_usfm/deut.usfm translation-tr.txt
node convert_to_usfm tr/jos.txt tr_usfm/jos.usfm translation-tr.txt
node convert_to_usfm tr/juiz.txt tr_usfm/juiz.usfm translation-tr.txt
node convert_to_usfm tr/rute.txt tr_usfm/rute.usfm translation-tr.txt
node convert_to_usfm tr/1sa.txt tr_usfm/1sa.usfm translation-tr.txt
node convert_to_usfm tr/2sa.txt tr_usfm/2sa.usfm translation-tr.txt
node convert_to_usfm tr/1rs.txt tr_usfm/1rs.usfm translation-tr.txt
node convert_to_usfm tr/2rs.txt tr_usfm/2rs.usfm translation-tr.txt
node convert_to_usfm tr/1crn.txt tr_usfm/1crn.usfm translation-tr.txt
node convert_to_usfm tr/2crn.txt tr_usfm/2crn.usfm translation-tr.txt
node convert_to_usfm tr/esd.txt tr_usfm/esd.usfm translation-tr.txt
node convert_to_usfm tr/nee.txt tr_usfm/nee.usfm translation-tr.txt
node convert_to_usfm tr/est.txt tr_usfm/est.usfm translation-tr.txt
node convert_to_usfm tr/jo.txt tr_usfm/jo.usfm translation-tr.txt
node convert_to_usfm tr/sal.txt tr_usfm/sal.usfm translation-tr.txt
node convert_to_usfm tr/prov.txt tr_usfm/prov.usfm translation-tr.txt
node convert_to_usfm tr/ecl.txt tr_usfm/ecl.usfm translation-tr.txt
node convert_to_usfm tr/cant.txt tr_usfm/cant.usfm translation-tr.txt
node convert_to_usfm tr/isa.txt tr_usfm/isa.usfm translation-tr.txt
node convert_to_usfm tr/jer.txt tr_usfm/jer.usfm translation-tr.txt
node convert_to_usfm tr/lam.txt tr_usfm/lam.usfm translation-tr.txt
node convert_to_usfm tr/eze.txt tr_usfm/eze.usfm translation-tr.txt
node convert_to_usfm tr/dan.txt tr_usfm/dan.usfm translation-tr.txt
node convert_to_usfm tr/ose.txt tr_usfm/ose.usfm translation-tr.txt
node convert_to_usfm tr/joel.txt tr_usfm/joel.usfm translation-tr.txt
node convert_to_usfm tr/amos.txt tr_usfm/amos.usfm translation-tr.txt
node convert_to_usfm tr/oba.txt tr_usfm/oba.usfm translation-tr.txt
node convert_to_usfm tr/jon.txt tr_usfm/jon.usfm translation-tr.txt
node convert_to_usfm tr/miq.txt tr_usfm/miq.usfm translation-tr.txt
node convert_to_usfm tr/naum.txt tr_usfm/naum.usfm translation-tr.txt
node convert_to_usfm tr/hab.txt tr_usfm/hab.usfm translation-tr.txt
node convert_to_usfm tr/sof.txt tr_usfm/sof.usfm translation-tr.txt
node convert_to_usfm tr/ageu.txt tr_usfm/ageu.usfm translation-tr.txt
node convert_to_usfm tr/zac.txt tr_usfm/zac.usfm translation-tr.txt
node convert_to_usfm tr/mal.txt tr_usfm/mal.usfm translation-tr.txt
node convert_to_usfm tr/mat.txt tr_usfm/mat.usfm translation-tr.txt
node convert_to_usfm tr/mar.txt tr_usfm/mar.usfm translation-tr.txt
node convert_to_usfm tr/luc.txt tr_usfm/luc.usfm translation-tr.txt
node convert_to_usfm tr/joao.txt tr_usfm/joao.usfm translation-tr.txt
node convert_to_usfm tr/atos.txt tr_usfm/atos.usfm translation-tr.txt
node convert_to_usfm tr/rom.txt tr_usfm/rom.usfm translation-tr.txt
node convert_to_usfm tr/1cor.txt tr_usfm/1cor.usfm translation-tr.txt
node convert_to_usfm tr/2cor.txt tr_usfm/2cor.usfm translation-tr.txt
node convert_to_usfm tr/gal.txt tr_usfm/gal.usfm translation-tr.txt
node convert_to_usfm tr/efes.txt tr_usfm/efes.usfm translation-tr.txt
node convert_to_usfm tr/fil.txt tr_usfm/fil.usfm translation-tr.txt
node convert_to_usfm tr/col.txt tr_usfm/col.usfm translation-tr.txt
node convert_to_usfm tr/1tes.txt tr_usfm/1tes.usfm translation-tr.txt
node convert_to_usfm tr/2tes.txt tr_usfm/2tes.usfm translation-tr.txt
node convert_to_usfm tr/1tim.txt tr_usfm/1tim.usfm translation-tr.txt
node convert_to_usfm tr/2tim.txt tr_usfm/2tim.usfm translation-tr.txt
node convert_to_usfm tr/tito.txt tr_usfm/tito.usfm translation-tr.txt
node convert_to_usfm tr/flm.txt tr_usfm/flm.usfm translation-tr.txt
node convert_to_usfm tr/heb.txt tr_usfm/heb.usfm translation-tr.txt
node convert_to_usfm tr/tiag.txt tr_usfm/tiag.usfm translation-tr.txt
node convert_to_usfm tr/1ped.txt tr_usfm/1ped.usfm translation-tr.txt
node convert_to_usfm tr/2ped.txt tr_usfm/2ped.usfm translation-tr.txt
node convert_to_usfm tr/1joao.txt tr_usfm/1joao.usfm translation-tr.txt
node convert_to_usfm tr/2joao.txt tr_usfm/2joao.usfm translation-tr.txt
node convert_to_usfm tr/3joao.txt tr_usfm/3joao.usfm translation-tr.txt
node convert_to_usfm tr/jud.txt tr_usfm/jud.usfm translation-tr.txt
node convert_to_usfm tr/apo.txt tr_usfm/apo.usfm translation-tr.txt

node convert_to_usfm n4/gen.txt n4_usfm/gen.usfm translation-n4.txt
node convert_to_usfm n4/exod.txt n4_usfm/exod.usfm translation-n4.txt
node convert_to_usfm n4/lev.txt n4_usfm/lev.usfm translation-n4.txt
node convert_to_usfm n4/num.txt n4_usfm/num.usfm translation-n4.txt
node convert_to_usfm n4/deut.txt n4_usfm/deut.usfm translation-n4.txt
node convert_to_usfm n4/jos.txt n4_usfm/jos.usfm translation-n4.txt
node convert_to_usfm n4/juiz.txt n4_usfm/juiz.usfm translation-n4.txt
node convert_to_usfm n4/rute.txt n4_usfm/rute.usfm translation-n4.txt
node convert_to_usfm n4/1sa.txt n4_usfm/1sa.usfm translation-n4.txt
node convert_to_usfm n4/2sa.txt n4_usfm/2sa.usfm translation-n4.txt
node convert_to_usfm n4/1rs.txt n4_usfm/1rs.usfm translation-n4.txt
node convert_to_usfm n4/2rs.txt n4_usfm/2rs.usfm translation-n4.txt
node convert_to_usfm n4/1crn.txt n4_usfm/1crn.usfm translation-n4.txt
node convert_to_usfm n4/2crn.txt n4_usfm/2crn.usfm translation-n4.txt
node convert_to_usfm n4/esd.txt n4_usfm/esd.usfm translation-n4.txt
node convert_to_usfm n4/nee.txt n4_usfm/nee.usfm translation-n4.txt
node convert_to_usfm n4/est.txt n4_usfm/est.usfm translation-n4.txt
node convert_to_usfm n4/jo.txt n4_usfm/jo.usfm translation-n4.txt
node convert_to_usfm n4/sal.txt n4_usfm/sal.usfm translation-n4.txt
node convert_to_usfm n4/prov.txt n4_usfm/prov.usfm translation-n4.txt
node convert_to_usfm n4/ecl.txt n4_usfm/ecl.usfm translation-n4.txt
node convert_to_usfm n4/cant.txt n4_usfm/cant.usfm translation-n4.txt
node convert_to_usfm n4/isa.txt n4_usfm/isa.usfm translation-n4.txt
node convert_to_usfm n4/jer.txt n4_usfm/jer.usfm translation-n4.txt
node convert_to_usfm n4/lam.txt n4_usfm/lam.usfm translation-n4.txt
node convert_to_usfm n4/eze.txt n4_usfm/eze.usfm translation-n4.txt
node convert_to_usfm n4/dan.txt n4_usfm/dan.usfm translation-n4.txt
node convert_to_usfm n4/ose.txt n4_usfm/ose.usfm translation-n4.txt
node convert_to_usfm n4/joel.txt n4_usfm/joel.usfm translation-n4.txt
node convert_to_usfm n4/amos.txt n4_usfm/amos.usfm translation-n4.txt
node convert_to_usfm n4/oba.txt n4_usfm/oba.usfm translation-n4.txt
node convert_to_usfm n4/jon.txt n4_usfm/jon.usfm translation-n4.txt
node convert_to_usfm n4/miq.txt n4_usfm/miq.usfm translation-n4.txt
node convert_to_usfm n4/naum.txt n4_usfm/naum.usfm translation-n4.txt
node convert_to_usfm n4/hab.txt n4_usfm/hab.usfm translation-n4.txt
node convert_to_usfm n4/sof.txt n4_usfm/sof.usfm translation-n4.txt
node convert_to_usfm n4/ageu.txt n4_usfm/ageu.usfm translation-n4.txt
node convert_to_usfm n4/zac.txt n4_usfm/zac.usfm translation-n4.txt
node convert_to_usfm n4/mal.txt n4_usfm/mal.usfm translation-n4.txt
node convert_to_usfm n4/mat.txt n4_usfm/mat.usfm translation-n4.txt
node convert_to_usfm n4/mar.txt n4_usfm/mar.usfm translation-n4.txt
node convert_to_usfm n4/luc.txt n4_usfm/luc.usfm translation-n4.txt
node convert_to_usfm n4/joao.txt n4_usfm/joao.usfm translation-n4.txt
node convert_to_usfm n4/atos.txt n4_usfm/atos.usfm translation-n4.txt
node convert_to_usfm n4/rom.txt n4_usfm/rom.usfm translation-n4.txt
node convert_to_usfm n4/1cor.txt n4_usfm/1cor.usfm translation-n4.txt
node convert_to_usfm n4/2cor.txt n4_usfm/2cor.usfm translation-n4.txt
node convert_to_usfm n4/gal.txt n4_usfm/gal.usfm translation-n4.txt
node convert_to_usfm n4/efes.txt n4_usfm/efes.usfm translation-n4.txt
node convert_to_usfm n4/fil.txt n4_usfm/fil.usfm translation-n4.txt
node convert_to_usfm n4/col.txt n4_usfm/col.usfm translation-n4.txt
node convert_to_usfm n4/1tes.txt n4_usfm/1tes.usfm translation-n4.txt
node convert_to_usfm n4/2tes.txt n4_usfm/2tes.usfm translation-n4.txt
node convert_to_usfm n4/1tim.txt n4_usfm/1tim.usfm translation-n4.txt
node convert_to_usfm n4/2tim.txt n4_usfm/2tim.usfm translation-n4.txt
node convert_to_usfm n4/tito.txt n4_usfm/tito.usfm translation-n4.txt
node convert_to_usfm n4/flm.txt n4_usfm/flm.usfm translation-n4.txt
node convert_to_usfm n4/heb.txt n4_usfm/heb.usfm translation-n4.txt
node convert_to_usfm n4/tiag.txt n4_usfm/tiag.usfm translation-n4.txt
node convert_to_usfm n4/1ped.txt n4_usfm/1ped.usfm translation-n4.txt
node convert_to_usfm n4/2ped.txt n4_usfm/2ped.usfm translation-n4.txt
node convert_to_usfm n4/1joao.txt n4_usfm/1joao.usfm translation-n4.txt
node convert_to_usfm n4/2joao.txt n4_usfm/2joao.usfm translation-n4.txt
node convert_to_usfm n4/3joao.txt n4_usfm/3joao.usfm translation-n4.txt
node convert_to_usfm n4/jud.txt n4_usfm/jud.usfm translation-n4.txt
node convert_to_usfm n4/apo.txt n4_usfm/apo.usfm translation-n4.txt
