node singleLineUSFM tr_usfm/gen.usfm tr_usfm_sl/02-GEN-bliv-tr.usfm
node singleLineUSFM tr_usfm/exod.usfm tr_usfm_sl/03-EXO-bliv-tr.usfm
node singleLineUSFM tr_usfm/lev.usfm tr_usfm_sl/04-LEV-bliv-tr.usfm
node singleLineUSFM tr_usfm/num.usfm tr_usfm_sl/05-NUM-bliv-tr.usfm
node singleLineUSFM tr_usfm/deut.usfm tr_usfm_sl/06-DEU-bliv-tr.usfm
node singleLineUSFM tr_usfm/jos.usfm tr_usfm_sl/07-JOS-bliv-tr.usfm
node singleLineUSFM tr_usfm/juiz.usfm tr_usfm_sl/08-JDG-bliv-tr.usfm
node singleLineUSFM tr_usfm/rute.usfm tr_usfm_sl/09-RUT-bliv-tr.usfm
node singleLineUSFM tr_usfm/1sa.usfm tr_usfm_sl/10-1SA-bliv-tr.usfm
node singleLineUSFM tr_usfm/2sa.usfm tr_usfm_sl/11-2SA-bliv-tr.usfm
node singleLineUSFM tr_usfm/1rs.usfm tr_usfm_sl/12-1KI-bliv-tr.usfm
node singleLineUSFM tr_usfm/2rs.usfm tr_usfm_sl/13-2KI-bliv-tr.usfm
node singleLineUSFM tr_usfm/1crn.usfm tr_usfm_sl/14-1CH-bliv-tr.usfm
node singleLineUSFM tr_usfm/2crn.usfm tr_usfm_sl/15-2CH-bliv-tr.usfm
node singleLineUSFM tr_usfm/esd.usfm tr_usfm_sl/16-EZR-bliv-tr.usfm
node singleLineUSFM tr_usfm/nee.usfm tr_usfm_sl/17-NEH-bliv-tr.usfm
node singleLineUSFM tr_usfm/est.usfm tr_usfm_sl/18-EST-bliv-tr.usfm
node singleLineUSFM tr_usfm/jo.usfm tr_usfm_sl/19-JOB-bliv-tr.usfm
node singleLineUSFM tr_usfm/sal.usfm tr_usfm_sl/20-PSA-bliv-tr.usfm
node singleLineUSFM tr_usfm/prov.usfm tr_usfm_sl/21-PRO-bliv-tr.usfm
node singleLineUSFM tr_usfm/ecl.usfm tr_usfm_sl/22-ECC-bliv-tr.usfm
node singleLineUSFM tr_usfm/cant.usfm tr_usfm_sl/23-SNG-bliv-tr.usfm
node singleLineUSFM tr_usfm/isa.usfm tr_usfm_sl/24-ISA-bliv-tr.usfm
node singleLineUSFM tr_usfm/jer.usfm tr_usfm_sl/25-JER-bliv-tr.usfm
node singleLineUSFM tr_usfm/lam.usfm tr_usfm_sl/26-LAM-bliv-tr.usfm
node singleLineUSFM tr_usfm/eze.usfm tr_usfm_sl/27-EZK-bliv-tr.usfm
node singleLineUSFM tr_usfm/dan.usfm tr_usfm_sl/28-DAN-bliv-tr.usfm
node singleLineUSFM tr_usfm/ose.usfm tr_usfm_sl/29-HOS-bliv-tr.usfm
node singleLineUSFM tr_usfm/joel.usfm tr_usfm_sl/30-JOL-bliv-tr.usfm
node singleLineUSFM tr_usfm/amos.usfm tr_usfm_sl/31-AMO-bliv-tr.usfm
node singleLineUSFM tr_usfm/oba.usfm tr_usfm_sl/32-OBA-bliv-tr.usfm
node singleLineUSFM tr_usfm/jon.usfm tr_usfm_sl/33-JON-bliv-tr.usfm
node singleLineUSFM tr_usfm/miq.usfm tr_usfm_sl/34-MIC-bliv-tr.usfm
node singleLineUSFM tr_usfm/naum.usfm tr_usfm_sl/35-NAM-bliv-tr.usfm
node singleLineUSFM tr_usfm/hab.usfm tr_usfm_sl/36-HAB-bliv-tr.usfm
node singleLineUSFM tr_usfm/sof.usfm tr_usfm_sl/37-ZEP-bliv-tr.usfm
node singleLineUSFM tr_usfm/ageu.usfm tr_usfm_sl/38-HAG-bliv-tr.usfm
node singleLineUSFM tr_usfm/zac.usfm tr_usfm_sl/39-ZEC-bliv-tr.usfm
node singleLineUSFM tr_usfm/mal.usfm tr_usfm_sl/40-MAL-bliv-tr.usfm
node singleLineUSFM tr_usfm/mat.usfm tr_usfm_sl/70-MAT-bliv-tr.usfm
node singleLineUSFM tr_usfm/mar.usfm tr_usfm_sl/71-MRK-bliv-tr.usfm
node singleLineUSFM tr_usfm/luc.usfm tr_usfm_sl/72-LUK-bliv-tr.usfm
node singleLineUSFM tr_usfm/joao.usfm tr_usfm_sl/73-JHN-bliv-tr.usfm
node singleLineUSFM tr_usfm/atos.usfm tr_usfm_sl/74-ACT-bliv-tr.usfm
node singleLineUSFM tr_usfm/rom.usfm tr_usfm_sl/75-ROM-bliv-tr.usfm
node singleLineUSFM tr_usfm/1cor.usfm tr_usfm_sl/76-1CO-bliv-tr.usfm
node singleLineUSFM tr_usfm/2cor.usfm tr_usfm_sl/77-2CO-bliv-tr.usfm
node singleLineUSFM tr_usfm/gal.usfm tr_usfm_sl/78-GAL-bliv-tr.usfm
node singleLineUSFM tr_usfm/efes.usfm tr_usfm_sl/79-EPH-bliv-tr.usfm
node singleLineUSFM tr_usfm/fil.usfm tr_usfm_sl/80-PHP-bliv-tr.usfm
node singleLineUSFM tr_usfm/col.usfm tr_usfm_sl/81-COL-bliv-tr.usfm
node singleLineUSFM tr_usfm/1tes.usfm tr_usfm_sl/82-1TH-bliv-tr.usfm
node singleLineUSFM tr_usfm/2tes.usfm tr_usfm_sl/83-2TH-bliv-tr.usfm
node singleLineUSFM tr_usfm/1tim.usfm tr_usfm_sl/84-1TI-bliv-tr.usfm
node singleLineUSFM tr_usfm/2tim.usfm tr_usfm_sl/85-2TI-bliv-tr.usfm
node singleLineUSFM tr_usfm/tito.usfm tr_usfm_sl/86-TIT-bliv-tr.usfm
node singleLineUSFM tr_usfm/flm.usfm tr_usfm_sl/87-PHM-bliv-tr.usfm
node singleLineUSFM tr_usfm/heb.usfm tr_usfm_sl/88-HEB-bliv-tr.usfm
node singleLineUSFM tr_usfm/tiag.usfm tr_usfm_sl/89-JAS-bliv-tr.usfm
node singleLineUSFM tr_usfm/1ped.usfm tr_usfm_sl/90-1PE-bliv-tr.usfm
node singleLineUSFM tr_usfm/2ped.usfm tr_usfm_sl/91-2PE-bliv-tr.usfm
node singleLineUSFM tr_usfm/1joao.usfm tr_usfm_sl/92-1JN-bliv-tr.usfm
node singleLineUSFM tr_usfm/2joao.usfm tr_usfm_sl/93-2JN-bliv-tr.usfm
node singleLineUSFM tr_usfm/3joao.usfm tr_usfm_sl/94-3JN-bliv-tr.usfm
node singleLineUSFM tr_usfm/jud.usfm tr_usfm_sl/95-JUD-bliv-tr.usfm
node singleLineUSFM tr_usfm/apo.usfm tr_usfm_sl/96-REV-bliv-tr.usfm

node singleLineUSFM n4_usfm/gen.usfm n4_usfm_sl/02-GEN-bliv-n4.usfm
node singleLineUSFM n4_usfm/exod.usfm n4_usfm_sl/03-EXO-bliv-n4.usfm
node singleLineUSFM n4_usfm/lev.usfm n4_usfm_sl/04-LEV-bliv-n4.usfm
node singleLineUSFM n4_usfm/num.usfm n4_usfm_sl/05-NUM-bliv-n4.usfm
node singleLineUSFM n4_usfm/deut.usfm n4_usfm_sl/06-DEU-bliv-n4.usfm
node singleLineUSFM n4_usfm/jos.usfm n4_usfm_sl/07-JOS-bliv-n4.usfm
node singleLineUSFM n4_usfm/juiz.usfm n4_usfm_sl/08-JDG-bliv-n4.usfm
node singleLineUSFM n4_usfm/rute.usfm n4_usfm_sl/09-RUT-bliv-n4.usfm
node singleLineUSFM n4_usfm/1sa.usfm n4_usfm_sl/10-1SA-bliv-n4.usfm
node singleLineUSFM n4_usfm/2sa.usfm n4_usfm_sl/11-2SA-bliv-n4.usfm
node singleLineUSFM n4_usfm/1rs.usfm n4_usfm_sl/12-1KI-bliv-n4.usfm
node singleLineUSFM n4_usfm/2rs.usfm n4_usfm_sl/13-2KI-bliv-n4.usfm
node singleLineUSFM n4_usfm/1crn.usfm n4_usfm_sl/14-1CH-bliv-n4.usfm
node singleLineUSFM n4_usfm/2crn.usfm n4_usfm_sl/15-2CH-bliv-n4.usfm
node singleLineUSFM n4_usfm/esd.usfm n4_usfm_sl/16-EZR-bliv-n4.usfm
node singleLineUSFM n4_usfm/nee.usfm n4_usfm_sl/17-NEH-bliv-n4.usfm
node singleLineUSFM n4_usfm/est.usfm n4_usfm_sl/18-EST-bliv-n4.usfm
node singleLineUSFM n4_usfm/jo.usfm n4_usfm_sl/19-JOB-bliv-n4.usfm
node singleLineUSFM n4_usfm/sal.usfm n4_usfm_sl/20-PSA-bliv-n4.usfm
node singleLineUSFM n4_usfm/prov.usfm n4_usfm_sl/21-PRO-bliv-n4.usfm
node singleLineUSFM n4_usfm/ecl.usfm n4_usfm_sl/22-ECC-bliv-n4.usfm
node singleLineUSFM n4_usfm/cant.usfm n4_usfm_sl/23-SNG-bliv-n4.usfm
node singleLineUSFM n4_usfm/isa.usfm n4_usfm_sl/24-ISA-bliv-n4.usfm
node singleLineUSFM n4_usfm/jer.usfm n4_usfm_sl/25-JER-bliv-n4.usfm
node singleLineUSFM n4_usfm/lam.usfm n4_usfm_sl/26-LAM-bliv-n4.usfm
node singleLineUSFM n4_usfm/eze.usfm n4_usfm_sl/27-EZK-bliv-n4.usfm
node singleLineUSFM n4_usfm/dan.usfm n4_usfm_sl/28-DAN-bliv-n4.usfm
node singleLineUSFM n4_usfm/ose.usfm n4_usfm_sl/29-HOS-bliv-n4.usfm
node singleLineUSFM n4_usfm/joel.usfm n4_usfm_sl/30-JOL-bliv-n4.usfm
node singleLineUSFM n4_usfm/amos.usfm n4_usfm_sl/31-AMO-bliv-n4.usfm
node singleLineUSFM n4_usfm/oba.usfm n4_usfm_sl/32-OBA-bliv-n4.usfm
node singleLineUSFM n4_usfm/jon.usfm n4_usfm_sl/33-JON-bliv-n4.usfm
node singleLineUSFM n4_usfm/miq.usfm n4_usfm_sl/34-MIC-bliv-n4.usfm
node singleLineUSFM n4_usfm/naum.usfm n4_usfm_sl/35-NAM-bliv-n4.usfm
node singleLineUSFM n4_usfm/hab.usfm n4_usfm_sl/36-HAB-bliv-n4.usfm
node singleLineUSFM n4_usfm/sof.usfm n4_usfm_sl/37-ZEP-bliv-n4.usfm
node singleLineUSFM n4_usfm/ageu.usfm n4_usfm_sl/38-HAG-bliv-n4.usfm
node singleLineUSFM n4_usfm/zac.usfm n4_usfm_sl/39-ZEC-bliv-n4.usfm
node singleLineUSFM n4_usfm/mal.usfm n4_usfm_sl/40-MAL-bliv-n4.usfm
node singleLineUSFM n4_usfm/mat.usfm n4_usfm_sl/70-MAT-bliv-n4.usfm
node singleLineUSFM n4_usfm/mar.usfm n4_usfm_sl/71-MRK-bliv-n4.usfm
node singleLineUSFM n4_usfm/luc.usfm n4_usfm_sl/72-LUK-bliv-n4.usfm
node singleLineUSFM n4_usfm/joao.usfm n4_usfm_sl/73-JHN-bliv-n4.usfm
node singleLineUSFM n4_usfm/atos.usfm n4_usfm_sl/74-ACT-bliv-n4.usfm
node singleLineUSFM n4_usfm/rom.usfm n4_usfm_sl/75-ROM-bliv-n4.usfm
node singleLineUSFM n4_usfm/1cor.usfm n4_usfm_sl/76-1CO-bliv-n4.usfm
node singleLineUSFM n4_usfm/2cor.usfm n4_usfm_sl/77-2CO-bliv-n4.usfm
node singleLineUSFM n4_usfm/gal.usfm n4_usfm_sl/78-GAL-bliv-n4.usfm
node singleLineUSFM n4_usfm/efes.usfm n4_usfm_sl/79-EPH-bliv-n4.usfm
node singleLineUSFM n4_usfm/fil.usfm n4_usfm_sl/80-PHP-bliv-n4.usfm
node singleLineUSFM n4_usfm/col.usfm n4_usfm_sl/81-COL-bliv-n4.usfm
node singleLineUSFM n4_usfm/1tes.usfm n4_usfm_sl/82-1TH-bliv-n4.usfm
node singleLineUSFM n4_usfm/2tes.usfm n4_usfm_sl/83-2TH-bliv-n4.usfm
node singleLineUSFM n4_usfm/1tim.usfm n4_usfm_sl/84-1TI-bliv-n4.usfm
node singleLineUSFM n4_usfm/2tim.usfm n4_usfm_sl/85-2TI-bliv-n4.usfm
node singleLineUSFM n4_usfm/tito.usfm n4_usfm_sl/86-TIT-bliv-n4.usfm
node singleLineUSFM n4_usfm/flm.usfm n4_usfm_sl/87-PHM-bliv-n4.usfm
node singleLineUSFM n4_usfm/heb.usfm n4_usfm_sl/88-HEB-bliv-n4.usfm
node singleLineUSFM n4_usfm/tiag.usfm n4_usfm_sl/89-JAS-bliv-n4.usfm
node singleLineUSFM n4_usfm/1ped.usfm n4_usfm_sl/90-1PE-bliv-n4.usfm
node singleLineUSFM n4_usfm/2ped.usfm n4_usfm_sl/91-2PE-bliv-n4.usfm
node singleLineUSFM n4_usfm/1joao.usfm n4_usfm_sl/92-1JN-bliv-n4.usfm
node singleLineUSFM n4_usfm/2joao.usfm n4_usfm_sl/93-2JN-bliv-n4.usfm
node singleLineUSFM n4_usfm/3joao.usfm n4_usfm_sl/94-3JN-bliv-n4.usfm
node singleLineUSFM n4_usfm/jud.usfm n4_usfm_sl/95-JUD-bliv-n4.usfm
node singleLineUSFM n4_usfm/apo.usfm n4_usfm_sl/96-REV-bliv-n4.usfm
